let money = 100000;
let income = 'Фриланс';
let addExpenses = 'Интернет, Такси, Коммуналка';
let deposit = true;
let mission = 1000000;
let period = 12;
console.log(money);
console.log(income);
console.log(deposit);
console.log(addExpenses.length);
console.log('Период равен ' + period + ' месяцев');
console.log('Цель заработать git ' + mission + ' рублей');
console.log(addExpenses.toLowerCase());
console.log(addExpenses.split(' '));
let budgetDay = money / 30;
console.log(budgetDay);
